-- Overlay events table for studio push-to-overlay functionality
-- Run this in Supabase SQL Editor

create table if not exists public.overlay_events (
  id bigint generated by default as identity primary key,
  room_id bigint not null references public.rooms(id) on delete cascade,
  event_type text not null,
  event_data jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_overlay_events_room on public.overlay_events(room_id, created_at desc);

alter table public.overlay_events enable row level security;

create policy "Public overlay events read" on public.overlay_events for select using (true);
create policy "Authenticated insert overlay events" on public.overlay_events for insert with check (auth.role() = 'authenticated');

ALTER PUBLICATION supabase_realtime ADD TABLE public.overlay_events;
