-- =============================================================
-- StreamArena — Full Schema Migration (consolidated)
-- Run this ONCE in Supabase Dashboard → SQL Editor
-- =============================================================

-- 0. Extensions
create extension if not exists "pgcrypto";

-- =============================================================
-- TABLES
-- =============================================================

-- 1. profiles
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text,
  avatar_url text,
  coins integer not null default 50,
  points integer not null default 0,
  streak integer not null default 0,
  created_at timestamptz not null default now()
);

-- 2. rooms
create table if not exists public.rooms (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null default 'Untitled Room',
  description text not null default '',
  host_id uuid references public.profiles(id) on delete set null,
  host_name text,
  host_avatar text,
  is_live boolean not null default true,
  viewer_count integer not null default 0,
  likes integer not null default 0,
  status text not null default 'queue_open',
  video_id text default '',
  created_at timestamptz not null default now()
);
create index if not exists idx_rooms_code on public.rooms(code);
create index if not exists idx_rooms_is_live on public.rooms(is_live);

-- 3. chat_messages
create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  room_id bigint not null references public.rooms(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete set null,
  username text not null,
  message text not null,
  amount integer not null default 0,
  color text not null default '#FF5A1F',
  is_super boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists idx_chat_room on public.chat_messages(room_id, created_at);

-- 4. queue_entries
create table if not exists public.queue_entries (
  id bigint generated by default as identity primary key,
  room_id bigint not null references public.rooms(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  username text not null,
  avatar_url text,
  type text not null default 'free',
  position integer not null,
  created_at timestamptz not null default now()
);
create index if not exists idx_queue_room on public.queue_entries(room_id, position);

-- 5. game_scores
create table if not exists public.game_scores (
  id bigint generated by default as identity primary key,
  room_id bigint not null references public.rooms(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  username text not null,
  game_type text not null,
  score integer not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists idx_scores_user on public.game_scores(user_id, created_at);

-- 6. leaderboard_entries
create table if not exists public.leaderboard_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  username text not null,
  total_points integer not null default 0,
  games_won integer not null default 0,
  streak integer not null default 0,
  period text not null default 'all',
  avatar_url text,
  created_at timestamptz not null default now()
);
create index if not exists idx_leaderboard_period on public.leaderboard_entries(period, total_points desc);
create unique index if not exists idx_leaderboard_user_period on public.leaderboard_entries(user_id, period);

-- 7. art_submissions (fan drops)
create table if not exists public.art_submissions (
  id bigint generated by default as identity primary key,
  room_id bigint not null references public.rooms(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete set null,
  username text not null,
  avatar_url text,
  image_url text,
  status text not null default 'pending',
  rating integer,
  content_type text default 'text',
  message text,
  emoji text,
  likes integer not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists idx_art_room on public.art_submissions(room_id, created_at);

-- 8. overlay_events
create table if not exists public.overlay_events (
  id bigint generated by default as identity primary key,
  room_id bigint not null references public.rooms(id) on delete cascade,
  event_type text not null,
  event_data jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists idx_overlay_events_room on public.overlay_events(room_id, created_at desc);

-- 9. submission_likes
create table if not exists public.submission_likes (
  id bigint generated by default as identity primary key,
  submission_id bigint not null references public.art_submissions(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(submission_id, user_id)
);
create index if not exists idx_submission_likes_submission on public.submission_likes(submission_id);
create index if not exists idx_submission_likes_user on public.submission_likes(user_id);

-- 10. room_likes
create table if not exists public.room_likes (
  room_id bigint not null references public.rooms(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (room_id, user_id)
);

-- 11. follows
create table if not exists public.follows (
  follower_id uuid not null references public.profiles(id) on delete cascade,
  following_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, following_id)
);

-- =============================================================
-- ROW LEVEL SECURITY
-- =============================================================

-- Enable RLS
alter table public.profiles enable row level security;
alter table public.rooms enable row level security;
alter table public.chat_messages enable row level security;
alter table public.art_submissions enable row level security;
alter table public.queue_entries enable row level security;
alter table public.game_scores enable row level security;
alter table public.leaderboard_entries enable row level security;
alter table public.overlay_events enable row level security;
alter table public.submission_likes enable row level security;
alter table public.room_likes enable row level security;
alter table public.follows enable row level security;

-- PROFILES
drop policy if exists "Anyone can view profiles" on profiles;
drop policy if exists "Users can update own profile" on profiles;
drop policy if exists "Users can insert own profile" on profiles;
create policy "Anyone can view profiles" on profiles for select using (true);
create policy "Users can insert own profile" on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

-- ROOMS
drop policy if exists "Anyone can view rooms" on rooms;
drop policy if exists "Authenticated users can create rooms" on rooms;
drop policy if exists "Host can update own room" on rooms;
create policy "Anyone can view rooms" on rooms for select using (true);
create policy "Authenticated users can create rooms" on rooms for insert with check (auth.role() = 'authenticated');
create policy "Host can update own room" on rooms for update using (auth.uid() = host_id);

-- CHAT MESSAGES
drop policy if exists "Anyone can view chat" on chat_messages;
drop policy if exists "Authenticated users can send chat" on chat_messages;
create policy "Anyone can view chat" on chat_messages for select using (true);
create policy "Authenticated users can send chat" on chat_messages for insert with check (auth.role() = 'authenticated');

-- ART SUBMISSIONS
drop policy if exists "Anyone can view art" on art_submissions;
drop policy if exists "Authenticated users can submit art" on art_submissions;
drop policy if exists "Host can update art in their room" on art_submissions;
drop policy if exists "Host can delete art in their room" on art_submissions;
create policy "Anyone can view art" on art_submissions for select using (true);
create policy "Authenticated users can submit art" on art_submissions for insert with check (auth.role() = 'authenticated');
create policy "Host can update art in their room" on art_submissions for update using (
  exists (select 1 from rooms where rooms.id = art_submissions.room_id and rooms.host_id = auth.uid())
);
create policy "Host can delete art in their room" on art_submissions for delete using (
  exists (select 1 from rooms where rooms.id = art_submissions.room_id and rooms.host_id = auth.uid())
);

-- QUEUE ENTRIES
drop policy if exists "Anyone can view queue" on queue_entries;
drop policy if exists "Authenticated users can join queue" on queue_entries;
drop policy if exists "Users can remove own queue entry" on queue_entries;
create policy "Anyone can view queue" on queue_entries for select using (true);
create policy "Authenticated users can join queue" on queue_entries for insert with check (auth.role() = 'authenticated');
create policy "Users can remove own queue entry" on queue_entries for delete using (auth.uid() = user_id);

-- GAME SCORES
drop policy if exists "Anyone can view scores" on game_scores;
drop policy if exists "Authenticated users can submit scores" on game_scores;
create policy "Anyone can view scores" on game_scores for select using (true);
create policy "Authenticated users can submit scores" on game_scores for insert with check (auth.role() = 'authenticated');

-- LEADERBOARD
drop policy if exists "Anyone can view leaderboard" on leaderboard_entries;
drop policy if exists "Users can insert leaderboard entry" on leaderboard_entries;
drop policy if exists "Users can update own leaderboard entry" on leaderboard_entries;
create policy "Anyone can view leaderboard" on leaderboard_entries for select using (true);
create policy "Users can insert leaderboard entry" on leaderboard_entries for insert with check (auth.role() = 'authenticated');
create policy "Users can update own leaderboard entry" on leaderboard_entries for update using (auth.uid() = user_id);

-- OVERLAY EVENTS
drop policy if exists "Anyone can view overlay events" on overlay_events;
drop policy if exists "Authenticated users can create overlay events" on overlay_events;
create policy "Anyone can view overlay events" on overlay_events for select using (true);
create policy "Authenticated users can create overlay events" on overlay_events for insert with check (auth.role() = 'authenticated');

-- SUBMISSION LIKES
drop policy if exists "Anyone can view likes" on submission_likes;
drop policy if exists "Authenticated users can like" on submission_likes;
drop policy if exists "Users can unlike own" on submission_likes;
create policy "Anyone can view likes" on submission_likes for select using (true);
create policy "Authenticated users can like" on submission_likes for insert with check (auth.role() = 'authenticated');
create policy "Users can unlike own" on submission_likes for delete using (auth.uid() = user_id);

-- ROOM LIKES
drop policy if exists "Anyone can view room_likes" on room_likes;
drop policy if exists "Users can like rooms" on room_likes;
drop policy if exists "Users can unlike rooms" on room_likes;
create policy "Anyone can view room_likes" on room_likes for select using (true);
create policy "Users can like rooms" on room_likes for insert with check (auth.uid() = user_id);
create policy "Users can unlike rooms" on room_likes for delete using (auth.uid() = user_id);

-- FOLLOWS
drop policy if exists "Anyone can view follows" on follows;
drop policy if exists "Users can follow" on follows;
drop policy if exists "Users can unfollow" on follows;
create policy "Anyone can view follows" on follows for select using (true);
create policy "Users can follow" on follows for insert with check (auth.uid() = follower_id);
create policy "Users can unfollow" on follows for delete using (auth.uid() = follower_id);

-- =============================================================
-- STORAGE (art-uploads bucket)
-- =============================================================

insert into storage.buckets (id, name, public)
values ('art-uploads', 'art-uploads', true)
on conflict (id) do nothing;

drop policy if exists "Anyone can view art uploads" on storage.objects;
drop policy if exists "Authenticated users can upload art" on storage.objects;
create policy "Anyone can view art uploads" on storage.objects for select using (bucket_id = 'art-uploads');
create policy "Authenticated users can upload art" on storage.objects for insert with check (bucket_id = 'art-uploads' and auth.role() = 'authenticated');

-- =============================================================
-- ATOMIC LIKES FUNCTION (prevents race conditions)
-- =============================================================

create or replace function public.increment_room_likes(room_id bigint, user_id uuid)
returns integer
language plpgsql
security definer
as $$
begin
  insert into public.room_likes (room_id, user_id) values (room_id, user_id);
  update public.rooms set likes = likes + 1 where id = room_id;
  return (select likes from public.rooms where id = room_id);
exception
  when unique_violation then
    return (select likes from public.rooms where id = room_id);
end;
$$;

create or replace function public.decrement_room_likes(room_id bigint, user_id uuid)
returns integer
language plpgsql
security definer
as $$
begin
  delete from public.room_likes where room_id = increment_room_likes.room_id and user_id = increment_room_likes.user_id;
  update public.rooms set likes = greatest(0, likes - 1) where id = room_id;
  return (select likes from public.rooms where id = room_id);
end;
$$;

-- =============================================================
-- AUTO-CREATE PROFILE ON USER SIGNUP
-- =============================================================

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, username, avatar_url, coins, points, streak)
  values (
    new.id,
    coalesce(split_part(new.email, '@', 1), 'User_' || substring(new.id::text, 1, 6)),
    'https://api.dicebear.com/7.x/avataaars/svg?seed=' || coalesce(split_part(new.email, '@', 1), new.id::text),
    200,
    0,
    0
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- =============================================================
-- DEDUCT COINS (atomic, prevents overdraft)
-- =============================================================

create or replace function public.deduct_coins(user_id uuid, amount integer)
returns integer
language plpgsql
security definer
as $$
declare
  current_coins integer;
begin
  select coins into current_coins from public.profiles where id = user_id;
  if not found then
    raise exception 'Profile not found';
  end if;
  if current_coins < amount then
    raise exception 'Insufficient coins: have %, need %', current_coins, amount;
  end if;
  update public.profiles set coins = coins - amount where id = user_id;
  return current_coins - amount;
end;
$$;

-- =============================================================
-- SUBMIT SCORE (atomic, updates leaderboard + profile)
-- =============================================================

create or replace function public.submit_score(
  p_room_id bigint,
  p_user_id uuid,
  p_username text,
  p_game_type text,
  p_score integer
)
returns void
language plpgsql
security definer
as $$
declare
  won integer;
begin
  insert into public.game_scores (room_id, user_id, username, game_type, score)
  values (p_room_id, p_user_id, p_username, p_game_type, p_score);

  won := case when p_score >= 100 then 1 else 0 end;

  insert into public.leaderboard_entries (user_id, username, total_points, games_won, streak, period, avatar_url)
  values (
    p_user_id, p_username, p_score, won, won,
    'all',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=' || coalesce(p_username, p_user_id::text)
  )
  on conflict (user_id, period) do update set
    total_points = leaderboard_entries.total_points + p_score,
    games_won = leaderboard_entries.games_won + won,
    streak = case when won = 1 then leaderboard_entries.streak + 1 else 0 end,
    username = p_username;

  update public.profiles set points = points + p_score where id = p_user_id;
end;
$$;

-- =============================================================
-- REALTIME PUBLICATION
-- =============================================================

do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'chat_messages') then
    alter publication supabase_realtime add table public.chat_messages;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'queue_entries') then
    alter publication supabase_realtime add table public.queue_entries;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'art_submissions') then
    alter publication supabase_realtime add table public.art_submissions;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'follows') then
    alter publication supabase_realtime add table public.follows;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'overlay_events') then
    alter publication supabase_realtime add table public.overlay_events;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'submission_likes') then
    alter publication supabase_realtime add table public.submission_likes;
  end if;
end;
$$;
