-- Add content columns to art_submissions
alter table public.art_submissions add column if not exists content_type text default 'text';
alter table public.art_submissions add column if not exists message text;
alter table public.art_submissions add column if not exists image_url text;
alter table public.art_submissions add column if not exists emoji text;
alter table public.art_submissions add column if not exists likes integer not null default 0;

-- Submission likes table
create table if not exists public.submission_likes (
  id bigint generated by default as identity primary key,
  submission_id bigint not null references public.art_submissions(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(submission_id, user_id)
);

create index if not exists idx_submission_likes_submission on public.submission_likes(submission_id);
create index if not exists idx_submission_likes_user on public.submission_likes(user_id);

alter table public.submission_likes enable row level security;

create policy "Anyone can view likes" on public.submission_likes for select using (true);
create policy "Authenticated users can like" on public.submission_likes for insert with check (auth.role() = 'authenticated');
create policy "Users can unlike own" on public.submission_likes for delete using (auth.uid() = user_id);

alter publication supabase_realtime add table public.submission_likes;
