-- =============================================================
-- StreamArena — Full Schema Migration
-- Paste this into Supabase Dashboard → SQL Editor and run
-- =============================================================

-- 0. Extensions
create extension if not exists "pgcrypto";

-- 1. profiles
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text,
  avatar_url text,
  coins integer not null default 200,
  points integer not null default 0,
  streak integer not null default 0,
  created_at timestamptz not null default now()
);

-- 2. rooms
create table if not exists public.rooms (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null default 'Untitled Room',
  description text not null default '',
  host_id uuid references public.profiles(id) on delete set null,
  host_name text,
  host_avatar text,
  is_live boolean not null default true,
  viewer_count integer not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists idx_rooms_code on public.rooms(code);
create index if not exists idx_rooms_is_live on public.rooms(is_live);

-- 3. chat_messages
create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  room_id bigint not null references public.rooms(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete set null,
  username text not null,
  message text not null,
  amount integer not null default 0,
  color text not null default '#FF5A1F',
  is_super boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists idx_chat_room on public.chat_messages(room_id, created_at);

-- 4. queue_entries
create table if not exists public.queue_entries (
  id bigint generated by default as identity primary key,
  room_id bigint not null references public.rooms(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  username text not null,
  avatar_url text,
  type text not null default 'free',
  position integer not null,
  created_at timestamptz not null default now()
);
create index if not exists idx_queue_room on public.queue_entries(room_id, position);

-- 5. game_scores
create table if not exists public.game_scores (
  id bigint generated by default as identity primary key,
  room_id bigint not null references public.rooms(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  username text not null,
  game_type text not null,
  score integer not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists idx_scores_user on public.game_scores(user_id, created_at);

-- 6. leaderboard_entries
create table if not exists public.leaderboard_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  username text not null,
  total_points integer not null default 0,
  games_won integer not null default 0,
  streak integer not null default 0,
  period text not null default 'all',
  avatar_url text,
  created_at timestamptz not null default now()
);
create index if not exists idx_leaderboard_period on public.leaderboard_entries(period, total_points desc);
create unique index if not exists idx_leaderboard_user_period on public.leaderboard_entries(user_id, period);

-- 7. art_submissions (fan drops)
create table if not exists public.art_submissions (
  id bigint generated by default as identity primary key,
  room_id bigint not null references public.rooms(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete set null,
  username text not null,
  avatar_url text,
  image_url text,
  status text not null default 'pending',
  rating integer,
  created_at timestamptz not null default now()
);
create index if not exists idx_art_room on public.art_submissions(room_id, created_at);

-- =============================================================
-- Row Level Security
-- =============================================================

-- Enable RLS on all tables
alter table public.profiles enable row level security;
alter table public.rooms enable row level security;
alter table public.chat_messages enable row level security;
alter table public.queue_entries enable row level security;
alter table public.game_scores enable row level security;
alter table public.leaderboard_entries enable row level security;
alter table public.art_submissions enable row level security;

-- Public read — anyone can view
create policy "Public profiles read" on public.profiles for select using (true);
create policy "Public rooms read" on public.rooms for select using (true);
create policy "Public chat read" on public.chat_messages for select using (true);
create policy "Public queue read" on public.queue_entries for select using (true);
create policy "Public scores read" on public.game_scores for select using (true);
create policy "Public leaderboard read" on public.leaderboard_entries for select using (true);
create policy "Public art read" on public.art_submissions for select using (true);

-- Authenticated insert/update/delete (fallback for direct client calls)
create policy "Users insert own profile" on public.profiles for insert with check (auth.uid() = id);
create policy "Users update own profile" on public.profiles for update using (auth.uid() = id);
create policy "Users insert chat" on public.chat_messages for insert with check (auth.uid() = user_id);
create policy "Users insert queue" on public.queue_entries for insert with check (auth.uid() = user_id);
create policy "Users delete own queue" on public.queue_entries for delete using (auth.uid() = user_id);
create policy "Users insert scores" on public.game_scores for insert with check (auth.uid() = user_id);
create policy "Users insert art" on public.art_submissions for insert with check (auth.uid() = user_id);

-- =============================================================
-- Storage bucket for art/fan-drop uploads
-- =============================================================

insert into storage.buckets (id, name, public)
values ('art-uploads', 'art-uploads', true)
on conflict (id) do nothing;

-- Allow public read
create policy "Public art files read"
on storage.objects for select using (bucket_id = 'art-uploads');

-- Allow authenticated uploads
create policy "Authenticated art files upload"
on storage.objects for insert with check (
  bucket_id = 'art-uploads'
  and auth.role() = 'authenticated'
);

-- =============================================================
-- Auto-create profile on user signup
-- =============================================================

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, username, avatar_url, coins, points, streak)
  values (
    new.id,
    coalesce(split_part(new.email, '@', 1), 'User_' || substring(new.id::text, 1, 6)),
    'https://api.dicebear.com/7.x/avataaars/svg?seed=' || coalesce(split_part(new.email, '@', 1), new.id::text),
    200,
    0,
    0
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

-- Trigger fires on every auth.users insert
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();
